Move bash version check to top of file
This will be needed later, since we'll be using syntax that this version
can no longer even parse so we need to early exit before it has a chance
to see that.

diff --git a/examples/multiline/multi b/examples/multiline/multi
--- a/examples/multiline/multi
+++ b/examples/multiline/multi
@@ -2,6 +2,11 @@
 # This script was generated by bashly (https://github.com/DannyBen/bashly)
 # Modifying it manually is not recommended
 
+if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
+  printf "bash version 4 or higher is required\n"
+  exit 1
+fi
+
 # :command.version_command
 version_command() {
   echo "$version"
@@ -373,11 +378,6 @@ initialize() {
   version="0.1.0"
   long_usage=''
   set -e
-
-  if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-    printf "bash version 4 or higher is required\n"
-    exit 1
-  fi
 
   # :src/initialize.sh
   # Code here runs inside the initialize() function
