- Redirect error messages to stderr

diff --git a/spec/approvals/script/wrapper/code b/spec/approvals/script/wrapper/code
--- a/spec/approvals/script/wrapper/code
+++ b/spec/approvals/script/wrapper/code
@@ -4,7 +4,7 @@
 
 # :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n"
+  printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
