- Update bash version bouncer to require bash 4.2

diff --git a/spec/approvals/script/wrapper/code b/spec/approvals/script/wrapper/code
--- a/spec/approvals/script/wrapper/code
+++ b/spec/approvals/script/wrapper/code
@@ -3,8 +3,8 @@
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if (( BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2) )); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
