fix usage header for proper display of fixed flags

diff --git a/examples/minus-v/cli b/examples/minus-v/cli
--- a/examples/minus-v/cli
+++ b/examples/minus-v/cli
@@ -16,41 +16,39 @@ version_command() {
 }
 
 # :command.usage
-download_usage() {
+cli_usage() {
   if [[ -n $long_usage ]]; then
-    printf "download - Sample minimal application with custom strings\n"
+    printf "cli - Example that replaces the default behavior of -v and -h\n"
     echo 
   else
-    printf "download - Sample minimal application with custom strings\n"
+    printf "cli - Example that replaces the default behavior of -v and -h\n"
     echo 
   fi
 
-  printf "== Usage ==\n\n"
-  printf "  download SOURCE [options]\n"
-  printf "  download --help | -h\n"
-  printf "  download --version | -v\n"
+  printf "Usage:\n"
+  printf "  cli [options]\n"
+  printf "  cli --help\n"
+  printf "  cli --version\n"
   echo
 
   if [[ -n $long_usage ]]; then
-    printf "== Options ==\n\n"
+    printf "Options:\n"
     # :command.usage_fixed_flags
-    echo "  --help, -h"
-    printf "    Show this helpful help\n"
+    echo "  --help"
+    printf "    Show this help\n"
     echo
-    echo "  --version, -v"
+    echo "  --version"
     printf "    Show version number\n"
     echo
     # :command.usage_flags
     # :flag.usage
-    echo "  --out, -o DIR (required)"
-    printf "    Target directory\n"
+    echo "  --verbose, -v"
+    printf "    Show verbose output\n"
     echo
-    # :command.usage_args
-    printf "== Arguments ==\n\n"
     
-    # :argument.usage
-    echo "  SOURCE"
-    printf "    URL to download from\n"
+    # :flag.usage
+    echo "  --host, -h HOST"
+    printf "    Host address\n"
     echo
 
   fi
@@ -68,14 +66,14 @@ inspect_args() {
 parse_requirements() {
   # :command.fixed_flag_filter
   case "$1" in
-  --version | -v )
+  --version )
     version_command
     exit 1
     ;;
   
-  --help | -h )
+  --help )
     long_usage=yes
-    download_usage
+    cli_usage
     exit 1
     ;;
   
@@ -85,31 +83,25 @@ parse_requirements() {
   # :command.command_filter
   action="root"
   # :command.required_args_filter
-  if [[ $1 && $1 != -* ]]; then
-    args[source]=$1
-    shift
-  else
-    printf "Boom! a required argument is missing: SOURCE\nusage: download SOURCE [options]\n"
-    exit 1
-  fi
   # :command.required_flags_filter
-  argstring="$*"
-  if [[ "$argstring" != *--out* && "$argstring" != *-o* ]]; then
-    printf "Yo! you forgot a flag: --out, -o DIR\n"
-    exit 1
-  fi
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
     # :flag.case
-    --out | -o )
+    --verbose | -v )
+      args[--verbose]=1
+      shift
+      ;;
+  
+    # :flag.case
+    --host | -h )
       if [[ $2 && $2 != -* ]]; then
-        args[--out]="$2"
+        args[--host]="$2"
         shift
         shift
       else
-        printf "%s\n" "Hey! the flag --out requires an argument: --out, -o DIR"
+        printf "%s\n" "--host requires an argument: --host, -h HOST"
         exit 1
       fi
       ;;
@@ -122,13 +114,8 @@ parse_requirements() {
   
     * )
       # :command.parse_requirements_case
-      if [[ ! ${args[source]} ]]; then
-        args[source]=$1
-        shift
-      else
-        printf "invalid argument: %s\n" "$key"
-        exit 1
-      fi
+      printf "invalid argument: %s\n" "$key"
+      exit 1
       ;;
   
     esac
@@ -159,7 +146,7 @@ run() {
     version_command
   elif [[ ${args[--help]} ]]; then
     long_usage=yes
-    download_usage
+    cli_usage
   elif [[ $action == "root" ]]; then
     root_command
   fi
